// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Update_Data")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_Data = new DateTime(2024, 1, 10, 13, 49, 50, 397, DateTimeKind.Local).AddTicks(8195),
                            Description = "Description for Villa 1",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Villa 1",
                            Occupancy = 4,
                            Price = 1000.0,
                            Sqft = 2000,
                            Update_Data = new DateTime(2024, 1, 10, 13, 49, 50, 397, DateTimeKind.Local).AddTicks(8206)
                        },
                        new
                        {
                            Id = 2,
                            Created_Data = new DateTime(2024, 1, 10, 13, 49, 50, 397, DateTimeKind.Local).AddTicks(8209),
                            Description = "Description for Villa 2",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Villa 2",
                            Occupancy = 4,
                            Price = 1000.0,
                            Sqft = 2000,
                            Update_Data = new DateTime(2024, 1, 10, 13, 49, 50, 397, DateTimeKind.Local).AddTicks(8209)
                        },
                        new
                        {
                            Id = 3,
                            Created_Data = new DateTime(2024, 1, 10, 13, 49, 50, 397, DateTimeKind.Local).AddTicks(8211),
                            Description = "Description for Villa 3",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Villa 3",
                            Occupancy = 4,
                            Price = 1000.0,
                            Sqft = 2000,
                            Update_Data = new DateTime(2024, 1, 10, 13, 49, 50, 397, DateTimeKind.Local).AddTicks(8211)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
